#!/usr/bin/env python3
import json
import sys
sys.path.insert(0, '../Q/Common')
sys.path.insert(0, '../Q/Referee')
sys.path.insert(0, '../Q/Player')
from json_io import Json_io
from referee import *

def main():
    input_objects = Json_io.decode_stacked(sys.stdin.read())
    parsed_objects = [elem for elem in input_objects]
    
    state = Json_io.from_j_state_and_players(parsed_objects[0], parsed_objects[1])
    
    show_observer = False
    
    if "--show" in sys.argv:
        show_observer = True
        
    referee = Referee([], state=state, display_observer=show_observer)

    winner, kicked_players = run_game(referee)

    print(json.dump([winner, kicked_players]), end='')

if __name__ == '__main__':
    main()